import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import NavBar from "./_ui/NavBar";
import { Box } from "@mui/material";
import CartContextProvider from "./_lib/CartContextProvider";
import SnackbarContextProvider from "./_lib/SnackBarProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartContextProvider>
          <SnackbarContextProvider>
            <NavBar />
            <Box sx={{ marginTop: "6em" }}>
              <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
            </Box>
          </SnackbarContextProvider>
        </CartContextProvider>
      </body>
    </html>
  );
}
